[Enhancement] Add RTC Seconds Interrupt
stm32duino/STM32RTC pull request #42
Opened 2020-09-24 06:38 UTC by josh-gaby

Implement the built-in Seconds interrupt functionality.

2020-10-02 11:26 UTC, josh-gaby commented
@fpistm 
What do you think about the idea of implementing a seconds interrupt using alarm B on other variants?

2020-10-02 11:30 UTC, fpistm commented
Well second interrupt for all should be fine for all series but to keep genericity this should not be dependent of a dedicated alarm.
And it is planned to support second alarm for all supported mode.

2020-10-02 11:37 UTC, josh-gaby commented
I'm fairly certain that only the F1xx series actually has a seconds interrupt, that's why I was thinking about using the unused alarm.

I went through a number of the other series in STM32CubeMX configuration and only the F1xx series seemed to have the seconds interrupt available. 

If it isn't available would it be best to only put support in for seconds interrupts on the F1xx series?

2020-10-02 12:18 UTC, fpistm commented
Right, I'm thinking about the periodic auto-wakeup which can be used for this. But maybe I'm wrong.

2020-10-02 12:32 UTC, josh-gaby commented
You may be onto something there, I ignored that option initially because I was thinking it only triggered an interrupt on PC13 but it seems that may be an optional feature. I'll look into using the PWUT to implement this feature for other variants.

2020-10-03 02:32 UTC, josh-gaby commented
I've only got a few different STM32F1xx based boards at the moment so can't test the Periodic wakeup timer, I'm waiting for some new dev boards to arrive in the mail before I can continue with this, might be a couple of weeks

2021-01-06 09:45 UTC, FRASTM approved these changes

2021-01-06 13:42 UTC, fpistm requested changes
Astyle change have to be fixed.

2021-01-06 13:42 UTC, fpistm commented on src/rtc.c
> +       If LL_RTC_WAKEUPCLOCK_CKSPRE is selected, the frequency is 1Hz,
```suggestion
       If LL_RTC_WAKEUPCLOCK_CKSPRE is selected, the frequency is 1Hz,
```

2021-01-06 13:42 UTC, fpistm commented on src/rtc.c
> +
```suggestion

```

2021-01-06 13:42 UTC, fpistm commented on src/rtc.c
> +
```suggestion

```

2021-01-06 13:42 UTC, fpistm commented on src/rtc.c
> +  HSE_CLOCK*/
```suggestion
  /* LSI_CLOCK,
   HSI_CLOCK,
   LSE_CLOCK,
   HSE_CLOCK*/
```

2021-01-06 13:42 UTC, fpistm commented on src/rtc.c
> +void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef* htim)
```suggestion
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
```

2021-01-06 13:42 UTC, fpistm commented on src/rtc.h
> +
```suggestion
```

2021-11-24 13:09 UTC, FRASTM reviewed
else LGTM
Do we have a test application to demonstrate this (for ex a simple LED on and off on each 1second interrupt

2021-11-24 13:09 UTC, FRASTM commented on src/rtc.c
> +  HAL_NVIC_EnableIRQ(RTC_IRQn);
The HAL_RTCEx_SetSecond_IT() function does not clear the SECF flag;
this could be done by `__HAL_RTC_SECOND_CLEAR_FLAG()`

2021-11-25 11:41 UTC, FRASTM commented
please have a look at https://github.com/FRASTM/STM32RTC/tree/seconds_int
including a simple example to display the Seconds Callback function
for the STM32F1

2021-12-15 16:23 UTC, fpistm commented
This one has been superseded by #57.

2021-12-15 16:23 UTC, closed without merging