C implementation of STM32RTC class
stm32duino/STM32RTC pull request #61
Opened 2021-12-31 11:06 UTC by MrZloHex

Hello,
I was writing a firmware for STM32 in C and I encountered a problem that there are no C libraries for internal RTC,
and i tried to rewrite your STM32RTC class from C++ into C Struct. In the near future i will add more functionality to be closely enough to your implementation.
I tested it on STM32G070RB - and it's all okay.

With respect, Alexey.

2022-01-02 21:25 UTC, MrZloHex commented
- [X] Import all methods

2022-01-03 17:00 UTC, fpistm commented
Hi @MrZloHex 
Is your firmware is to be used in Arduino ecosytem?

As a first look your porting change the default import of the Arduino library: STM32RTC.h becomes STM32RTC.hpp so the default examples can't compile as no C++ API are available.

2022-01-04 15:59 UTC, MrZloHex commented
Yes, I'm using arduino ecosystem.

I made STM32RTC.h into .hpp to differentiate C andd C++ implementation.
I could change C impl into STM32RTC_c.h and make C++ version as STM32RTC.h if you want.
Or simply change examples.

2022-01-04 16:09 UTC, fpistm commented
> Or simply change examples.

No, several examples are available outside this library and several users/fw using this library include only the STM32RTC.h file. So this is not an options.

Honestly I wonder if it is a good idea to mix/duplicate code in this library. It is really confusing. Just talking about how Arduino include the library, it uses the STM32RTC.h as main entry to include it. So how you would manage this to only include the C part ? 
Maybe the only way would be to have only one.h file and using `#ifdef __cplusplus`

2022-01-06 11:56 UTC, MrZloHex commented
I merged 2 headers into 1 with `__cplusplus` and STB-style macro to divide C++ and C implementations.
Now all examples work and to use C version before include you should `#define C_IMPLEMENTATION` to confirm that you to use c version.

2022-01-06 13:17 UTC, fpistm requested changes
An example using C interface could be fine to add.

2022-01-06 13:17 UTC, fpistm commented on src/STM32RTC.h
> +#if defined(__cplusplus) && !defined(C_IMPLEMENTATION)
I don't think it is needed to add an extra definition
```suggestion
#if defined(__cplusplus)
```

2022-01-06 13:17 UTC, fpistm commented on src/STM32RTC.h
> +typedef signed long    i64;
Avoid to define new type. Use standard one: uint8_t, int16_t,....
Please replace them in all definition and declaration

2022-07-29 14:25 UTC, fpistm commented
Closed as no update since a while.

2022-07-29 14:25 UTC, closed without merging